### ISSUE TITLE
SyntaxError: 'import' and 'export' may only appear at the top level 

### ISSUE THREAD

**Issue by koraykupe** [Herteby/vue-clicky#3]
Hello,

When I add that statement to my js file, it gives "SyntaxError: 'import' and 'export' may only appear at the top level" error on build. Any solution?

`if (process.env.NODE_ENV === 'development') {
import 'vue-clicky'
}`

Regards.

**Comment by Herteby** [comment]
Btw, I just decided to rewrite vue-clicky quite a bit. If you update to the latest version (2.0.1) you can do like this:
```
import clicky from 'vue-clicky'

if (process.env.NODE_ENV === 'development'){
  clicky()
}
```
Clicky would still be imported in production, but it's just 80 lines.

**Comment by koraykupe** [comment]
Thanks a lot!
